image: docker:stable

stages:
  - build

variables:
  STAGING_BASEURL: http://toflit18-pprd.medialab.sciences-po.fr
  CLIENT_IMAGE_NAME: $CI_REGISTRY/scpomedialab/toflit18-client:$CI_COMMIT_REF_SLUG
  API_IMAGE_NAME: $CI_REGISTRY/scpomedialab/toflit18-api:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_CERTDIR: ""

services:
    - docker:stable-dind

build_client_staging:
  stage: build
  script:
    - docker build -t $CLIENT_IMAGE_NAME -f ./client/Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push $CLIENT_IMAGE_NAME
  environment:
    name: staging
    url: $STAGING_BASEURL
  only:
    - master
    - staging
    - prod

build_api_staging:
  stage: build
  script:
    - docker build -t $API_IMAGE_NAME -f Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push $API_IMAGE_NAME
  environment:
    name: staging
    url: $STAGING_BASEURL
  only:
    - master
    - staging
    - prod
