version: '2'
services:
  client:
    build: client
    restart: unless-stopped
    links:
      - api
    ports:
      - 80:80
    volumes_from:
      - api
  api:
    build: .
    restart: unless-stopped
    environment:
      - NEO4J_HOST=db
    ports:
      - 4000:4000
  db:
    image: neo4j:3.1.3
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=4096M
      - NEO4J_dbms_memory_heap_maxSize=4096M
    volumes:
      - ./neo4j_data:/data/databases/
    ports:
      - 7474:7474
      - 7687:7687
