apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toflit18

namePrefix: toflit18-

bases:
  - ../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: production

secretGenerator:
- name: neo4j
  env: neo4j.env

- name: toflit18
  env: toflit18.env

images:
  - name: scpomedialab/toflit18-api
    newTag: 'prod'
  - name: scpomedialab/toflit18-client
    newTag: 'prod'
  - name: gitlab.sciences-po.fr:4567/medialab/toflit18_data/neo4j_toflit18
    newTag: 'prod'
